### ISSUE TITLE
Failures when using ASBS 2.x as a publisher when auditing is enabled

### ISSUE THREAD

**Issue by FabianTrottmann** [Particular/NServiceBus.Transport.Bridge#159]
Setup: Eventing between Azure Service Bus and msmq using NSB.Transport.bridge.

Faulty scenario:
MSMQ subscribes to an event that is published by an Azure Service Bus EP. MSMQ EP therefore uses RegisterPublisher, which triggers a subscription message. The subscription message is consumed by the bridge and forwarded to a queue in the Azure service bus.
The message is then consumed by the service bus EP. That works as long as the service bus EP does not audit these messages. When the message is audited using `AuditProcessedMessagesTo("auditqueue")`, the following error occurs:

```txt
System.ArgumentNullException: Value cannot be null.
Parameter name: messageId
   at Azure.Core.Amqp.AmqpMessageId..ctor(String messageId)
   at Azure.Messaging.ServiceBus.ServiceBusMessage.set_CorrelationId(String value)
   at NServiceBus.Transport.AzureServiceBus.OutgoingMessageExtensions.ToAzureServiceBusMessage`
```

My understanding is that subscription messages are not needed in the context of Azure Service Bus and have no impact. Event subscriptions take place without these messages.
So I see the following options:

1. Using pipeline behavior to filter out control messages from being audited.
2. The MSMQ EP does not use RegiterPublisher when registering an event which is sent by azure service bus (leads to warnings)
3. Bridge does not pass control messages to Azure Service Bus

Option 2 leads to the fact, that the MSMQ EP does know about the bridge, which shouldn't be the case.

**Comment by ramonsmits** [comment]
@FabianTrottmann Do you know if the sample has the same behavior when auditing is enabled?

- https://docs.particular.net/samples/bridge/azure-service-bus-msmq-bridge/

> My understanding is that subscription messages are not needed in the context of Azure Service Bus

That is correct, it uses native pubsub where the subscriber subscribes to it on the broker.

The bridge should work with auditing enabled. In your scenario it seems the bridge is forwarding the subscription message to the EP which likely should not be happening.

**Comment by FabianTrottmann** [comment]
@ramonsmits forgot to mention that I used NSB 7.8 for MSMQ and ASB EP. 
I Just tested with ASB EP v8.0 and MSMQ EP v7.8, with this setup, the subscription message is sent as well but can be consumed by ASB EP without exceptions.

The mentioned sample has the same behavior, when downgrading the ASB EP to v7.8 and auditing enabled.
So for me this would work, to use v8 für ASB EP. For MSMQ EP we have to stick to v7.8 atm.

**Comment by dvdstelt** [comment]
What you're seeing is the audit message of the subscription message. I didn't even know we send those. But apparently we didn't test with audit messages at all, or we would've spotted this. We did test regular error message bridging and even performance metrics forwarding, but seem to have failed testing this.
I created a pull request with a fix, but it needs a review and perhaps a test, although I don't know how to write a fair/true test at this moment. It's quite late in my evening already. ;-)

**Comment by ramonsmits** [comment]
- Resolved by #160

**Comment by ramonsmits** [comment]
@FabianTrottmann Fixed in https://github.com/Particular/NServiceBus.Transport.Bridge/releases/tag/0.1.1

**Comment by FabianTrottmann** [comment]
@ramonsmits This is still an issue
the subscription message coming from an MSMQ endpoint is forwarded through the bridge to an ASB endpoint. The ASB endpoint processes the subscription messages and attempts to send the subscription message to the audit queue, at which point an error occurs (see exception above).

This only happens with ASB EP v7.8 (in v8.0 the subscription is handled and sent to audit queue without an issue).

It can easily be reproducedt with this example https://docs.particular.net/samples/bridge/azure-service-bus-msmq-bridge/ just go back to asb v7.8 and configure an audit queue in the ASB EP.

I think the bridge should not send subscription messages to ASB Endpoints, what do you think?

**Comment by ramonsmits** [comment]
@FabianTrottmann I updated the repro with that earlier modified sample and confirm that the issue isn't resolved:

- https://github.com/Particular/docs.particular.net/tree/bridge-issues-159/samples/bridge/azure-service-bus-msmq-bridge/Bridge_1

**Comment by dvdstelt** [comment]
@FabianTrottmann We just released 1.0.1 which should fix issues you had.
